### ISSUE TITLE
Import BiLouvain raises error

### ISSUE THREAD

**Issue by riozhu-GZ** [ijcruic/Multi-view-Clustering-of-Social-Based-Data#1]
It seems like sknetwork.clustering doesn't support BiLouvain clustering methods. Could you please suggest a new clustering method? Thanks.

**Comment by riozhu-GZ** [comment]
here: 
------------------------------
0.24.0 (2021-07-27)[](https://scikit-network.readthedocs.io/en/latest/history.html#id14)
Merge Bi* algorithms (e.g., BiLouvain -> Louvain) by Thomas Bonald (#490)

Transition from Travis to Github actions by Quentin Lutz (#488)

Added sdist build for conda recipes

Added name position for graph visualization

Removed randomized algorithms
------------------------------

should be Louvain

**Comment by ijcruic** [comment]
Good looking out! It needed a couple of changes to account for the updates to Sci-Kit Network; change to Louvain as well as change in how modularity is calculated. 

It should be good now, and please let me know if its not!

Also, I'll get a tutorial on how to use the code into the Repo soon as well.
